language: cpp
script: make unit
dist: trusty

before_install:
  - eval "${MATRIX_EVAL}"

matrix:
  include:
    - os: linux
      name: Linux

    - os: osx
      osx_image: xcode11
      name: OSX


    - os: linux
      name: Clang 6
      dist: xenial
      addons:
        apt:
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - os: linux
      name: GCC 4.9
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      dist: xenial
      name: GCC 9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - TREAT_WARNINGS_AS_ERRORS=1

    - os: linux
      name: GCC 9 32 Bit
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9 libc6-dev-i386 g++-9-multilib gcc-9-multilib gcc-multilib g++-multilib lib32readline6-dev lib32readline6
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      script:
        - mkdir -p build/release
        - (cd build/release && cmake -DFORCE_32_BIT=1 -DCMAKE_BUILD_TYPE=Release ../.. && cmake --build .)
        - build/release/test/unittest

    - os: windows
      name: VS 2017
      language: c
      before_script:
        - choco install python3 --version 3.7.3 -y --params "/InstallDir:C:\Python37-x64"
      script:
        - C:/Python37-x64/python.exe scripts/amalgamation.py
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64
        - cmake --build . --target duckdb --config Release
        - cmake --build . --target unittest --config Release
        - test/Release/unittest.exe
    - os: windows
      name: VS 2017 (32 Bit)
      language: c
      before_script:
        - choco install python3 --version 3.7.3 -y --params "/InstallDir:C:\Python37-x64"
        - choco install curl -y --force
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=Win32
        - cmake --build . --target duckdb --config Release
        - cmake --build . --target unittest --config Release
        - cmake --build . --target shell --config Release
        - test/Release/unittest.exe


